### ISSUE TITLE
Doesn't work - Bad magic number in .pyc file

### ISSUE THREAD

**Issue by joaovrsoares** [WKS410/PlutoTV-Ripper#1]
Script doesn't work, it shows me this error:

>C:\Users\Administrador\Desktop>main.pyc
>RuntimeError: Bad magic number in .pyc file
>
>C:\Users\Administrador\Desktop>main.pyc https://pluto.tv/pt/on-demand/series/marvel-anime-x-men-br/details/season/1
>RuntimeError: Bad magic number in .pyc file

Is there a solution? Can you post the original .py file?
I'm using Python 3.11.2.
> C:\Users\Administrador>python --version
>Python 3.11.2

**Comment by WKS410** [comment]
D:\>python --version
Python 3.7.9

and does not work with links
you have to look for it as you can see in the screenshots
